Code refactoring component
chris-kuehn/capstone-project pull request #13
Opened 2023-08-28 14:20 UTC by chris-kuehn

2023-08-28 14:37 UTC, F-Kirchhoff requested changes
Hey Chirstian,
this looks already pretty good. I like how you use the hsl colors with the variables. Please check my suggestions, you can remove some unnecessary code.

2023-08-28 14:37 UTC, F-Kirchhoff commented on components/Section.js
> +}
you can export the component "StudioGeneratorSection" directly. You don't need to create a second Component here called Wrapper. You can do that like this:
```js

const StudioGeneratorSection = styled.div`
  ...styling
`
export default StudioGeneratorSection
```
Keep in mind that a default export can be imported under any name you like, they can be "renamed when imported" so to speak. So it doesn't matter which variable name you choose here, when you import it you can choose a different name.

2023-08-28 14:37 UTC, F-Kirchhoff commented on components/SectionHeadline.js
> +`;
Here its the same for the headline (but you must write the headline text between the Component tags like this: `<SectionHeadline>This is the text</SectionHeadline>`

2023-08-29 10:05 UTC, chris-kuehn commented
Thank you for the feedback and the explinations! :)

I implemented everything :)

2023-08-29 10:22 UTC, merged